name: godot-ci

on:
  push:
    branches: [ main ]

env:
  EXPORT_NAME: modded-platformer-demo
  GODOT_VERSION: 4.4.1 # NOTE: Still using a potentially invalid Godot version

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    
    # NOTE: This 'container' block CONFLICTS with the 'game-ci/setup-godot@v2' action.
    container:
      image: barichello/godot-ci:4.4.1
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Cache Godot export templates
        uses: actions/cache@v4
        with:
          path: ~/.local/share/godot/export_templates
          key: godot-templates-${{ env.GODOT_VERSION }}-${{ runner.os }}-${{ hashFiles('.github/workflows/godot-ci.yml') }}

      - name: Setup Godot and export templates
        uses: game-ci/setup-godot@v2
        with:
          godot-version: ${{ env.GODOT_VERSION }}
          export-templates: true
      
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y rsync
      
      - name: Debug: list export templates
        run: |
          echo "Templates dir:"
          ls -la "$HOME/.local/share/godot/export_templates" || true
          ls -la "$HOME/.local/share/godot/export_templates/${GODOT_VERSION}.stable" || true
      
      - name: Build Web Export
        run: |
          mkdir -p build/web
          godot -v --headless --export-release "Web" build/web/index.html
      
      - name: Debug: show build output
        run: ls -la build/web || true
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/web
      
      - name: Publish to itch.io
        if: success()
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerAPIKey: ${{ secrets.BUTLER_API_KEY }} # Corrected secret name convention
          itchUsername: judahsan
          itchGameId: modded-platformer-demo
          buildChannel: web
          gameData: build/web
