name: Build and Deploy to itch.io

on:
  push:
    branches:
      - main

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: '4.4.0'
          include-templates: true

      - name: Export game (Web)
        run: |
          mkdir -p exports/web
          godot --headless --export-release "Web" exports/web/index.html

          # TROUBLESHOOTING: Check if the files were created
          echo "--- Export Directory Contents ---"
          ls -R exports/web/
          echo "---------------------------------"

      # OPTIONAL: Add other exports here
      # - name: Export game (Linux)
      #   run: |
      #     mkdir -p exports/linux
      #     godot --headless --export-release "Linux/X11" exports/linux/game.x86_64

      - name: Install butler
        run: |
          curl -L https://broth.itch.ovh/butler/linux-amd64/latest/archive/default | tar xz
          sudo mv butler /usr/local/bin/

      - name: Push to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.ITCHIO_TOKEN }}
        run: |
          butler push exports/web judahsan/modded-platformer-demo:web
