name: Godot CI / Web Deployment

on:
  push:
    branches: [ main ]

env:
  GODOT_PROJECT_PATH: project/
  EXPORT_NAME: modded-platformer-demo

jobs:
  export-web:
    name: Web Export & Publish
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Web Export
        uses: abarichello/godot-ci@v4
        with:
          godot-version: 4.2.1
          project-path: ${{ env.GODOT_PROJECT_PATH }}
          export-platform: HTML5
          export-path: build/web/index.html
          export-name: ${{ env.EXPORT_NAME }}

      - name: Publish to itch.io
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerAPIKey: ${{ secrets.ITCHIO_TOKEN }}
          itchUsername: judahsan
          itchGameId: modded-platformer-demo
          buildChannel: web
          gameData: ${{ env.GODOT_PROJECT_PATH }}build/web/
