name: "Godot CI Export & Deploy to Itch.io"

on:
  workfow_dispatch:
  push:
    # branches: [ "main" ]

env:
  GODOT_VERSION: 4.4
  EXPORT_NAME: godopong
  PROJECT_PATH: .

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup export templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Export Web
        run: |
          mkdir -p build/web
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --export-release "Web" "$EXPORT_DIR/web/index.html"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/web

      - name: Deploy to Itch.io 🎮
        uses: Ayowel/butler-publish-itchio@v1.1.0
        with:
          api_key: ${{ secrets.ITCH_IO_API_KEY }}
          user: your-itch-username
          game: godopong
          channel: web
          path: build/web
